import streamlit as st
from fpdf import FPDF
from datetime import datetime
import os

# ========================= FUNCTIONS (MUST BE AT THE TOP) =========================
def calculate_heating_load(data):
    q_walls = data['u_walls'] * data['area_walls'] * (data['t_indoor'] - data['t_outdoor'])
    q_windows = data['u_windows'] * data['area_windows'] * (data['t_indoor'] - data['t_outdoor'])
    q_roof = data['u_roof'] * data['area_roof'] * (data['t_indoor'] - data['t_outdoor'])
    q_conduction = q_walls + q_windows + q_roof
    cfm = (data['volume'] * data['ach']) / 60
    q_infil = 1.08 * cfm * (data['t_indoor'] - data['t_outdoor'])
    total = q_conduction + q_infil
    return {'total_btu_hr': round(total), 'cfm': round(cfm, 1)}

def calculate_cooling_load(data):
    q_walls = data['u_walls'] * data['area_walls'] * 25
    q_roof = data['u_roof'] * data['area_roof'] * 40
    q_windows = data['u_windows'] * data['area_windows'] * 12
    q_solar = data['area_windows'] * 140
    cfm = (data['volume'] * data['ach']) / 60
    delta_t = data['t_outdoor'] - data['t_indoor']
    q_inf_s = 1.08 * cfm * delta_t
    q_inf_l = 0.68 * cfm * 30
    q_people = data['occupants'] * 380
    sensible = q_walls + q_roof + q_windows + q_solar + q_inf_s + q_people
    total = sensible + q_inf_l
    return {
        'total_btu_hr': round(total),
        'tons': round(total / 12000, 2),
        'cfm': round(sensible / (1.08 * 20))
    }

def generate_pdf_report(data, result, mode):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "VetCool HVAC LOAD REPORT", ln=True, align="C")
    pdf.ln(10)

    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 8, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
    pdf.cell(0, 8, f"Type: {mode}", ln=True)
    pdf.ln(10)

    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "INPUT PARAMETERS", ln=True)
    pdf.set_font("Arial", "", 11)
    for key, value in data.items():
        if key not in ["mode"]:
            nice_key = key.replace('_', ' ').title()
            pdf.cell(0, 6, f"• {nice_key}: {value}", ln=True)

    pdf.ln(10)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "RESULTS", ln=True)
    pdf.set_font("Arial", "", 11)

    if "Heating" in mode:
        pdf.cell(0, 8, f"Total Heating Load: {result.get('total_btu_hr')} BTU/hr", ln=True)
        pdf.cell(0, 8, f"Airflow: {result.get('cfm')} CFM", ln=True)
    else:
        pdf.cell(0, 8, f"Total Cooling Load: {result.get('total_btu_hr')} BTU/hr", ln=True)
        pdf.cell(0, 8, f"Tons: {result.get('tons')} Tons", ln=True)
        pdf.cell(0, 8, f"Airflow: {result.get('cfm')} CFM", ln=True)

    pdf.ln(20)
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 8, "Generated by VetCool HVAC Calculator", ln=True, align="C")

    filename = f"vetcool_report_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf"
    pdf.output(filename)
    return filename

# ========================= STREAMLIT APP =========================
st.set_page_config(page_title="VetCool HVAC Calculator", page_icon="🔧", layout="centered")

st.markdown("""
<style>
    .stApp { background-color: #0E1117; color: #FFFFFF; }
    .stButton>button { background-color: #E30613; color: white; font-weight: bold; }
    .stButton>button:hover { background-color: #FF1A1A; }
    h1, h2, h3 { color: #FFFFFF; }
</style>
""", unsafe_allow_html=True)

try:
    st.image("vetcool_logo.png", width=280)
except:
    pass

st.title("VetCool HVAC Load Calculator")
st.markdown("**Professional Heating & Cooling Load Estimator**")

# Quick Presets and UI code here (the rest of your app)
st.subheader("Quick Presets")
preset = st.selectbox("Choose a common scenario", [
    "Custom Input", "Small House (1200 sq ft)", "Medium House (2000 sq ft)", 
    "Large House (3000 sq ft)", "Small Office", "Restaurant", "Warehouse"
])

# ... (rest of your UI code - I shortened it here for message length, but you can keep your previous UI)

st.caption("© VetCool Refrigerant")